# Generated by Django 6.0.1 on 2026-02-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imovel_contrato_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('LOCADOR', 'Locador'), ('LOCATARIO', 'Locatário')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('LOCADOR', 'Locador'), ('LOCATARIO', 'Locatário')], max_length=20),
        ),
    ]
